apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prod
  namespace: flux-system
spec:
  interval: 5s
  ref:
    branch: master
  url: https://github.com/bclavijo110430/cicd-flow
